/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as EnviosRouteImport } from './routes/envios'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductoSlugRouteImport } from './routes/producto.$slug'
import { Route as MarcaSlugRouteImport } from './routes/marca.$slug'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as AdminSplatRouteImport } from './routes/admin.$'
import { Route as AdminProductosIndexRouteImport } from './routes/admin.productos.index'
import { Route as AdminProductosNuevoRouteImport } from './routes/admin.productos.nuevo'
import { Route as AdminProductosImportarRouteImport } from './routes/admin.productos.importar'
import { Route as AdminProductosEditarIdRouteImport } from './routes/admin.productos.editar.$id'

const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const EnviosRoute = EnviosRouteImport.update({
  id: '/envios',
  path: '/envios',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductoSlugRoute = ProductoSlugRouteImport.update({
  id: '/producto/$slug',
  path: '/producto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcaSlugRoute = MarcaSlugRouteImport.update({
  id: '/marca/$slug',
  path: '/marca/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductosIndexRoute = AdminProductosIndexRouteImport.update({
  id: '/productos/',
  path: '/productos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductosNuevoRoute = AdminProductosNuevoRouteImport.update({
  id: '/productos/nuevo',
  path: '/productos/nuevo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductosImportarRoute = AdminProductosImportarRouteImport.update({
  id: '/productos/importar',
  path: '/productos/importar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductosEditarIdRoute = AdminProductosEditarIdRouteImport.update({
  id: '/productos/editar/$id',
  path: '/productos/editar/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/envios': typeof EnviosRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/admin/$': typeof AdminSplatRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/marca/$slug': typeof MarcaSlugRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/productos/importar': typeof AdminProductosImportarRoute
  '/admin/productos/nuevo': typeof AdminProductosNuevoRoute
  '/admin/productos/': typeof AdminProductosIndexRoute
  '/admin/productos/editar/$id': typeof AdminProductosEditarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/envios': typeof EnviosRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/admin/$': typeof AdminSplatRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/marca/$slug': typeof MarcaSlugRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/productos/importar': typeof AdminProductosImportarRoute
  '/admin/productos/nuevo': typeof AdminProductosNuevoRoute
  '/admin/productos': typeof AdminProductosIndexRoute
  '/admin/productos/editar/$id': typeof AdminProductosEditarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/envios': typeof EnviosRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/admin/$': typeof AdminSplatRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/marca/$slug': typeof MarcaSlugRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/productos/importar': typeof AdminProductosImportarRoute
  '/admin/productos/nuevo': typeof AdminProductosNuevoRoute
  '/admin/productos/': typeof AdminProductosIndexRoute
  '/admin/productos/editar/$id': typeof AdminProductosEditarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contacto'
    | '/envios'
    | '/sobre-nosotros'
    | '/admin/$'
    | '/categoria/$slug'
    | '/marca/$slug'
    | '/producto/$slug'
    | '/admin/'
    | '/admin/productos/importar'
    | '/admin/productos/nuevo'
    | '/admin/productos/'
    | '/admin/productos/editar/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/envios'
    | '/sobre-nosotros'
    | '/admin/$'
    | '/categoria/$slug'
    | '/marca/$slug'
    | '/producto/$slug'
    | '/admin'
    | '/admin/productos/importar'
    | '/admin/productos/nuevo'
    | '/admin/productos'
    | '/admin/productos/editar/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contacto'
    | '/envios'
    | '/sobre-nosotros'
    | '/admin/$'
    | '/categoria/$slug'
    | '/marca/$slug'
    | '/producto/$slug'
    | '/admin/'
    | '/admin/productos/importar'
    | '/admin/productos/nuevo'
    | '/admin/productos/'
    | '/admin/productos/editar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  EnviosRoute: typeof EnviosRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  MarcaSlugRoute: typeof MarcaSlugRoute
  ProductoSlugRoute: typeof ProductoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envios': {
      id: '/envios'
      path: '/envios'
      fullPath: '/envios'
      preLoaderRoute: typeof EnviosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/producto/$slug': {
      id: '/producto/$slug'
      path: '/producto/$slug'
      fullPath: '/producto/$slug'
      preLoaderRoute: typeof ProductoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marca/$slug': {
      id: '/marca/$slug'
      path: '/marca/$slug'
      fullPath: '/marca/$slug'
      preLoaderRoute: typeof MarcaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/productos/': {
      id: '/admin/productos/'
      path: '/productos'
      fullPath: '/admin/productos/'
      preLoaderRoute: typeof AdminProductosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/productos/nuevo': {
      id: '/admin/productos/nuevo'
      path: '/productos/nuevo'
      fullPath: '/admin/productos/nuevo'
      preLoaderRoute: typeof AdminProductosNuevoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/productos/importar': {
      id: '/admin/productos/importar'
      path: '/productos/importar'
      fullPath: '/admin/productos/importar'
      preLoaderRoute: typeof AdminProductosImportarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/productos/editar/$id': {
      id: '/admin/productos/editar/$id'
      path: '/productos/editar/$id'
      fullPath: '/admin/productos/editar/$id'
      preLoaderRoute: typeof AdminProductosEditarIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSplatRoute: typeof AdminSplatRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProductosImportarRoute: typeof AdminProductosImportarRoute
  AdminProductosNuevoRoute: typeof AdminProductosNuevoRoute
  AdminProductosIndexRoute: typeof AdminProductosIndexRoute
  AdminProductosEditarIdRoute: typeof AdminProductosEditarIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSplatRoute: AdminSplatRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProductosImportarRoute: AdminProductosImportarRoute,
  AdminProductosNuevoRoute: AdminProductosNuevoRoute,
  AdminProductosIndexRoute: AdminProductosIndexRoute,
  AdminProductosEditarIdRoute: AdminProductosEditarIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactoRoute: ContactoRoute,
  EnviosRoute: EnviosRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  MarcaSlugRoute: MarcaSlugRoute,
  ProductoSlugRoute: ProductoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
