/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as EnviosRouteImport } from './routes/envios'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarcaSlugRouteImport } from './routes/marca.$slug'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'

const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const EnviosRoute = EnviosRouteImport.update({
  id: '/envios',
  path: '/envios',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcaSlugRoute = MarcaSlugRouteImport.update({
  id: '/marca/$slug',
  path: '/marca/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/envios': typeof EnviosRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/marca/$slug': typeof MarcaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/envios': typeof EnviosRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/marca/$slug': typeof MarcaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/envios': typeof EnviosRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/marca/$slug': typeof MarcaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/envios'
    | '/sobre-nosotros'
    | '/categoria/$slug'
    | '/marca/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/envios'
    | '/sobre-nosotros'
    | '/categoria/$slug'
    | '/marca/$slug'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/envios'
    | '/sobre-nosotros'
    | '/categoria/$slug'
    | '/marca/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  EnviosRoute: typeof EnviosRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  MarcaSlugRoute: typeof MarcaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envios': {
      id: '/envios'
      path: '/envios'
      fullPath: '/envios'
      preLoaderRoute: typeof EnviosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marca/$slug': {
      id: '/marca/$slug'
      path: '/marca/$slug'
      fullPath: '/marca/$slug'
      preLoaderRoute: typeof MarcaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  EnviosRoute: EnviosRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  MarcaSlugRoute: MarcaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
